### ISSUE TITLE
Command ['kuskus'] load symbols from cluster resulted in an error (command kuskus.loadsymbols' not found

### ISSUE THREAD

**Issue by le0li9ht** [rosshamish/kuskus#74]
When I am selecting the kuskus pack from ctrl+shift+P its resulting this error.

**Comment by rosshamish** [comment]
Hi @le0li9ht - I just merged a speculative fix for this in #148 and released it as v2.0.3 https://marketplace.visualstudio.com/items?itemName=rosshamish.kuskus-kusto-language-server

If you're still using this, consider updating the extension and letting me know if the fix is good on your end. If you still see issues, let me know and I'll re-open. Thanks.

**Comment by rosshamish** [comment]
Reopening - I updated myself to 2.0.3 and see this issue still. I didn't see this in a local dev environment though, so something must be wrong with the publish step.

**Comment by rosshamish** [comment]
speculative fix for is released in v2.0.4

**Comment by rosshamish** [comment]
Fixed in 2.0.5
